(function(){
'use strict';
if(window.mxMobileLite&&window.mxMobileLite.__fastV1078)return;
const mem=new Map(),pending=new Map();
const txt=v=>String(v==null?'':v).trim(),norm=v=>txt(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/\s+/g,' ');
function cfg(){try{const c=window.mxViewerGetCfg?.()||{};return{db:txt(c.db||c.firebaseUrl||c.currentUrl||c.url).replace(/\.json\/?$/i,'').replace(/\/+$/,''),branch:txt(c.branch||c.unitId||c.activationId||c.storeId||'HGAM').toUpperCase()||'HGAM'}}catch(_e){return{db:'',branch:'HGAM'}}}
function serviceKey(v){const s=norm(v)||'ALL';try{return btoa(unescape(encodeURIComponent(s))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}catch(_e){return s.replace(/[.#$\[\]\/]/g,'_')}}
function rest(path){const c=cfg();if(!c.db)throw new Error('Esperando conexión con el Sistema Principal');return c.db+'/'+String(path||'').replace(/^\/+/, '')+'.json'}
async function get(path,timeout=5000){const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(rest(path)+'?mx='+Date.now(),{cache:'no-store',signal:ctl.signal});if(!r.ok)throw new Error('Firebase HTTP '+r.status);return await r.json().catch(()=>null)}finally{clearTimeout(tm)}}
async function put(path,data,timeout=5000){const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(rest(path),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:ctl.signal});if(!r.ok)throw new Error('Firebase HTTP '+r.status);return await r.json().catch(()=>null)}finally{clearTimeout(tm)}}
const id=()=> 'mq_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,9);
function cget(k,ttl){const r=mem.get(k);return r&&Date.now()-r.at<ttl?r.value:null}
function cset(k,v){mem.set(k,{at:Date.now(),value:v});return v}
function ttlFor(type){type=norm(type).toLowerCase();if(type==='product'||type==='patient')return 120000;if(type==='patient_history'||type==='patient_orders')return 45000;return 20000}
function parseStreamEvent(ev){try{const pack=JSON.parse(ev?.data||'null');if(!pack)return null;const d=pack&&Object.prototype.hasOwnProperty.call(pack,'data')?pack.data:pack;return d&&typeof d==='object'?d:null}catch(_e){return null}}
function waitResponse(path,totalTimeout=7500){return new Promise((resolve,reject)=>{let done=false,es=null,pollTimer=null,timeoutTimer=null,polling=false;const finish=(err,val)=>{if(done)return;done=true;clearTimeout(pollTimer);clearTimeout(timeoutTimer);try{es?.close()}catch(_e){};err?reject(err):resolve(val)};const accept=v=>{if(!v||typeof v!=='object')return false;const st=String(v.status||'').toLowerCase();if(st==='done'){finish(null,v);return true}if(st==='error'){finish(new Error(txt(v.message)||'Error de consulta'));return true}return false};const poll=async()=>{if(done||polling)return;polling=true;try{accept(await get(path,1800).catch(()=>null))}finally{polling=false;if(!done)pollTimer=setTimeout(poll,150)}};try{if(typeof EventSource==='function'){es=new EventSource(rest(path));const onData=e=>accept(parseStreamEvent(e));es.addEventListener('put',onData);es.addEventListener('patch',onData);es.onmessage=onData;es.onerror=()=>{try{es?.close()}catch(_e){};es=null}}}catch(_e){};pollTimer=setTimeout(poll,110);timeoutTimer=setTimeout(()=>finish(new Error('El Sistema Principal no respondió a la consulta')),totalTimeout)})}
async function top(kind,service='',opts={}){const c=cfg(),sk=serviceKey(service),k=`top|${c.branch}|${kind}|${sk}`,hit=!opts.force&&cget(k,45000);if(hit)return hit;let r=await get(`/mobile_views/${encodeURIComponent(c.branch)}/${kind}/${sk}`,3500).catch(()=>null);if((!r||!Array.isArray(r.items))&&sk!==serviceKey('ALL'))r=await get(`/mobile_views/${encodeURIComponent(c.branch)}/${kind}/${serviceKey('ALL')}`,3500).catch(()=>null);return cset(k,{items:Array.isArray(r?.items)?r.items:[],updatedAt:txt(r?.updatedAt),service:txt(r?.service),source:txt(r?.source||'SISTEMA_PRINCIPAL')})}
async function query(type,q='',service='',opts={}){const c=cfg(),needle=txt(q),limit=Math.max(1,Math.min(30,Number(opts.limit)||20)),extra=opts.extra&&typeof opts.extra==='object'?opts.extra:{},key=`q|${c.branch}|${type}|${norm(needle)}|${serviceKey(service)}|${JSON.stringify(extra)}`,hit=!opts.force&&cget(key,ttlFor(type));if(hit)return hit;if(pending.has(key))return pending.get(key);const task=(async()=>{const rid=id(),now=new Date().toISOString(),body={id:rid,status:'pending',type:txt(type).toLowerCase(),q:needle,service:txt(service),limit,createdAt:now,createdAtMs:Date.now(),...extra};await put(`/mobile_query_requests/${encodeURIComponent(c.branch)}/${rid}`,body,4000);await put(`/mobile_query_ping/${encodeURIComponent(c.branch)}`,{v:Date.now(),id:rid,at:now},2500).catch(()=>{});const response=await waitResponse(`/mobile_query_responses/${encodeURIComponent(c.branch)}/${rid}`,7600);setTimeout(()=>{put(`/mobile_query_requests/${encodeURIComponent(c.branch)}/${rid}`,null,1800).catch(()=>{});put(`/mobile_query_responses/${encodeURIComponent(c.branch)}/${rid}`,null,1800).catch(()=>{})},700);return cset(key,response)})();pending.set(key,task);try{return await task}finally{pending.delete(key)}}
const searchProducts=(q,s='',o={})=>query('product',q,s,o),searchPatients=(q,s='',o={})=>query('patient',q,s,o),patientHistory=(patientKey,patient='',expediente='',o={})=>query('patient_history','',o.service||'',{...o,extra:{patientKey:txt(patientKey),patient:txt(patient),expediente:txt(expediente)}});
function clear(){mem.clear()}
window.mxMobileLite={cfg,serviceKey,get,put,top,query,searchProducts,searchPatients,patientHistory,clear,norm,__fastV1078:true};window.addEventListener('mx-viewer-config-changed',clear);window.addEventListener('mx-viewer-binding-updated',clear);
})();
